// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: live_channels.sql

package sqlc_postgres

import (
	"context"
	"database/sql"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO live_channels (
    library_id,
    channel_number,
    name,
    stream_url,
    logo_url,
    channel_group,
    epg_channel_id,
    enabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, library_id, channel_number, name, stream_url, logo_url, channel_group, epg_channel_id, enabled, created_at, updated_at
`

type CreateChannelParams struct {
	LibraryID     int64          `json:"library_id"`
	ChannelNumber int64          `json:"channel_number"`
	Name          string         `json:"name"`
	StreamUrl     string         `json:"stream_url"`
	LogoUrl       sql.NullString `json:"logo_url"`
	ChannelGroup  sql.NullString `json:"channel_group"`
	EpgChannelID  sql.NullString `json:"epg_channel_id"`
	Enabled       int64          `json:"enabled"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (LiveChannel, error) {
	row := q.db.QueryRowContext(ctx, createChannel,
		arg.LibraryID,
		arg.ChannelNumber,
		arg.Name,
		arg.StreamUrl,
		arg.LogoUrl,
		arg.ChannelGroup,
		arg.EpgChannelID,
		arg.Enabled,
	)
	var i LiveChannel
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.ChannelNumber,
		&i.Name,
		&i.StreamUrl,
		&i.LogoUrl,
		&i.ChannelGroup,
		&i.EpgChannelID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM live_channels
WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteChannel, id)
	return err
}

const deleteChannelsByLibrary = `-- name: DeleteChannelsByLibrary :exec
DELETE FROM live_channels
WHERE library_id = $1
`

func (q *Queries) DeleteChannelsByLibrary(ctx context.Context, libraryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteChannelsByLibrary, libraryID)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, library_id, channel_number, name, stream_url, logo_url, channel_group, epg_channel_id, enabled, created_at, updated_at FROM live_channels
WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id int64) (LiveChannel, error) {
	row := q.db.QueryRowContext(ctx, getChannel, id)
	var i LiveChannel
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.ChannelNumber,
		&i.Name,
		&i.StreamUrl,
		&i.LogoUrl,
		&i.ChannelGroup,
		&i.EpgChannelID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChannelByEPGID = `-- name: GetChannelByEPGID :one
SELECT id, library_id, channel_number, name, stream_url, logo_url, channel_group, epg_channel_id, enabled, created_at, updated_at FROM live_channels
WHERE library_id = $1 AND epg_channel_id = $2
`

type GetChannelByEPGIDParams struct {
	LibraryID    int64          `json:"library_id"`
	EpgChannelID sql.NullString `json:"epg_channel_id"`
}

func (q *Queries) GetChannelByEPGID(ctx context.Context, arg GetChannelByEPGIDParams) (LiveChannel, error) {
	row := q.db.QueryRowContext(ctx, getChannelByEPGID, arg.LibraryID, arg.EpgChannelID)
	var i LiveChannel
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.ChannelNumber,
		&i.Name,
		&i.StreamUrl,
		&i.LogoUrl,
		&i.ChannelGroup,
		&i.EpgChannelID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChannels = `-- name: ListChannels :many
SELECT id, library_id, channel_number, name, stream_url, logo_url, channel_group, epg_channel_id, enabled, created_at, updated_at FROM live_channels
WHERE library_id = $1
ORDER BY channel_number ASC, name ASC
`

func (q *Queries) ListChannels(ctx context.Context, libraryID int64) ([]LiveChannel, error) {
	rows, err := q.db.QueryContext(ctx, listChannels, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LiveChannel{}
	for rows.Next() {
		var i LiveChannel
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.ChannelNumber,
			&i.Name,
			&i.StreamUrl,
			&i.LogoUrl,
			&i.ChannelGroup,
			&i.EpgChannelID,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertChannel = `-- name: UpsertChannel :one
INSERT INTO live_channels (
    library_id,
    channel_number,
    name,
    stream_url,
    logo_url,
    channel_group,
    epg_channel_id,
    enabled
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT(library_id, name) DO UPDATE SET
    channel_number = EXCLUDED.channel_number,
    stream_url = EXCLUDED.stream_url,
    logo_url = EXCLUDED.logo_url,
    channel_group = EXCLUDED.channel_group,
    epg_channel_id = EXCLUDED.epg_channel_id,
    enabled = EXCLUDED.enabled,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, library_id, channel_number, name, stream_url, logo_url, channel_group, epg_channel_id, enabled, created_at, updated_at
`

type UpsertChannelParams struct {
	LibraryID     int64          `json:"library_id"`
	ChannelNumber int64          `json:"channel_number"`
	Name          string         `json:"name"`
	StreamUrl     string         `json:"stream_url"`
	LogoUrl       sql.NullString `json:"logo_url"`
	ChannelGroup  sql.NullString `json:"channel_group"`
	EpgChannelID  sql.NullString `json:"epg_channel_id"`
	Enabled       int64          `json:"enabled"`
}

func (q *Queries) UpsertChannel(ctx context.Context, arg UpsertChannelParams) (LiveChannel, error) {
	row := q.db.QueryRowContext(ctx, upsertChannel,
		arg.LibraryID,
		arg.ChannelNumber,
		arg.Name,
		arg.StreamUrl,
		arg.LogoUrl,
		arg.ChannelGroup,
		arg.EpgChannelID,
		arg.Enabled,
	)
	var i LiveChannel
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.ChannelNumber,
		&i.Name,
		&i.StreamUrl,
		&i.LogoUrl,
		&i.ChannelGroup,
		&i.EpgChannelID,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
