// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: live_channel_epg_mapping.sql

package sqlc_postgres

import (
	"context"
	"database/sql"
)

const createChannelEPGMapping = `-- name: CreateChannelEPGMapping :one
INSERT INTO live_channel_epg_mapping (
    library_id,
    xmltv_channel_id,
    channel_id
) VALUES ($1, $2, $3)
RETURNING id, library_id, xmltv_channel_id, channel_id, created_at
`

type CreateChannelEPGMappingParams struct {
	LibraryID      int64  `json:"library_id"`
	XmltvChannelID string `json:"xmltv_channel_id"`
	ChannelID      int64  `json:"channel_id"`
}

func (q *Queries) CreateChannelEPGMapping(ctx context.Context, arg CreateChannelEPGMappingParams) (LiveChannelEpgMapping, error) {
	row := q.db.QueryRowContext(ctx, createChannelEPGMapping, arg.LibraryID, arg.XmltvChannelID, arg.ChannelID)
	var i LiveChannelEpgMapping
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.XmltvChannelID,
		&i.ChannelID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteChannelEPGMapping = `-- name: DeleteChannelEPGMapping :exec
DELETE FROM live_channel_epg_mapping
WHERE library_id = $1 AND xmltv_channel_id = $2
`

type DeleteChannelEPGMappingParams struct {
	LibraryID      int64  `json:"library_id"`
	XmltvChannelID string `json:"xmltv_channel_id"`
}

func (q *Queries) DeleteChannelEPGMapping(ctx context.Context, arg DeleteChannelEPGMappingParams) error {
	_, err := q.db.ExecContext(ctx, deleteChannelEPGMapping, arg.LibraryID, arg.XmltvChannelID)
	return err
}

const deleteChannelEPGMappingsByLibrary = `-- name: DeleteChannelEPGMappingsByLibrary :exec
DELETE FROM live_channel_epg_mapping
WHERE library_id = $1
`

func (q *Queries) DeleteChannelEPGMappingsByLibrary(ctx context.Context, libraryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteChannelEPGMappingsByLibrary, libraryID)
	return err
}

const getChannelEPGMapping = `-- name: GetChannelEPGMapping :one
SELECT id, library_id, xmltv_channel_id, channel_id, created_at FROM live_channel_epg_mapping
WHERE library_id = $1 AND xmltv_channel_id = $2
`

type GetChannelEPGMappingParams struct {
	LibraryID      int64  `json:"library_id"`
	XmltvChannelID string `json:"xmltv_channel_id"`
}

func (q *Queries) GetChannelEPGMapping(ctx context.Context, arg GetChannelEPGMappingParams) (LiveChannelEpgMapping, error) {
	row := q.db.QueryRowContext(ctx, getChannelEPGMapping, arg.LibraryID, arg.XmltvChannelID)
	var i LiveChannelEpgMapping
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.XmltvChannelID,
		&i.ChannelID,
		&i.CreatedAt,
	)
	return i, err
}

const getEPGMappingForLibrary = `-- name: GetEPGMappingForLibrary :many
SELECT xmltv_channel_id, channel_id
FROM live_channel_epg_mapping
WHERE library_id = $1
`

type GetEPGMappingForLibraryRow struct {
	XmltvChannelID string `json:"xmltv_channel_id"`
	ChannelID      int64  `json:"channel_id"`
}

func (q *Queries) GetEPGMappingForLibrary(ctx context.Context, libraryID int64) ([]GetEPGMappingForLibraryRow, error) {
	rows, err := q.db.QueryContext(ctx, getEPGMappingForLibrary, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEPGMappingForLibraryRow{}
	for rows.Next() {
		var i GetEPGMappingForLibraryRow
		if err := rows.Scan(&i.XmltvChannelID, &i.ChannelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelEPGMappings = `-- name: ListChannelEPGMappings :many
SELECT m.id, m.library_id, m.xmltv_channel_id, m.channel_id, m.created_at, c.name as channel_name, c.stream_url
FROM live_channel_epg_mapping m
JOIN live_channels c ON c.id = m.channel_id
WHERE m.library_id = $1
ORDER BY m.xmltv_channel_id
`

type ListChannelEPGMappingsRow struct {
	ID             int64        `json:"id"`
	LibraryID      int64        `json:"library_id"`
	XmltvChannelID string       `json:"xmltv_channel_id"`
	ChannelID      int64        `json:"channel_id"`
	CreatedAt      sql.NullTime `json:"created_at"`
	ChannelName    string       `json:"channel_name"`
	StreamUrl      string       `json:"stream_url"`
}

func (q *Queries) ListChannelEPGMappings(ctx context.Context, libraryID int64) ([]ListChannelEPGMappingsRow, error) {
	rows, err := q.db.QueryContext(ctx, listChannelEPGMappings, libraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelEPGMappingsRow{}
	for rows.Next() {
		var i ListChannelEPGMappingsRow
		if err := rows.Scan(
			&i.ID,
			&i.LibraryID,
			&i.XmltvChannelID,
			&i.ChannelID,
			&i.CreatedAt,
			&i.ChannelName,
			&i.StreamUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannelEPGMapping = `-- name: UpdateChannelEPGMapping :one
UPDATE live_channel_epg_mapping
SET channel_id = $1
WHERE library_id = $2 AND xmltv_channel_id = $3
RETURNING id, library_id, xmltv_channel_id, channel_id, created_at
`

type UpdateChannelEPGMappingParams struct {
	ChannelID      int64  `json:"channel_id"`
	LibraryID      int64  `json:"library_id"`
	XmltvChannelID string `json:"xmltv_channel_id"`
}

func (q *Queries) UpdateChannelEPGMapping(ctx context.Context, arg UpdateChannelEPGMappingParams) (LiveChannelEpgMapping, error) {
	row := q.db.QueryRowContext(ctx, updateChannelEPGMapping, arg.LibraryID, arg.XmltvChannelID, arg.ChannelID)
	var i LiveChannelEpgMapping
	err := row.Scan(
		&i.ID,
		&i.LibraryID,
		&i.XmltvChannelID,
		&i.ChannelID,
		&i.CreatedAt,
	)
	return i, err
}
