// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: live_epg_programs.sql

package sqlc_postgres

import (
	"context"
	"database/sql"
	"time"
)

const bulkCreatePrograms = `-- name: BulkCreatePrograms :exec
INSERT INTO live_epg_programs (
    channel_id,
    start_time,
    end_time,
    title,
    sub_title,
    description,
    category,
    episode_title,
    episode_num,
    season_num,
    is_new,
    is_movie
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type BulkCreateProgramsParams struct {
	ChannelID    int64          `json:"channel_id"`
	StartTime    time.Time      `json:"start_time"`
	EndTime      time.Time      `json:"end_time"`
	Title        string         `json:"title"`
	SubTitle     sql.NullString `json:"sub_title"`
	Description  sql.NullString `json:"description"`
	Category     sql.NullString `json:"category"`
	EpisodeTitle sql.NullString `json:"episode_title"`
	EpisodeNum   sql.NullInt64  `json:"episode_num"`
	SeasonNum    sql.NullInt64  `json:"season_num"`
	IsNew        sql.NullInt64  `json:"is_new"`
	IsMovie      sql.NullInt64  `json:"is_movie"`
}

func (q *Queries) BulkCreatePrograms(ctx context.Context, arg BulkCreateProgramsParams) error {
	_, err := q.db.ExecContext(ctx, bulkCreatePrograms,
		arg.ChannelID,
		arg.StartTime,
		arg.EndTime,
		arg.Title,
		arg.SubTitle,
		arg.Description,
		arg.Category,
		arg.EpisodeTitle,
		arg.EpisodeNum,
		arg.SeasonNum,
		arg.IsNew,
		arg.IsMovie,
	)
	return err
}

const createProgram = `-- name: CreateProgram :one
INSERT INTO live_epg_programs (
    channel_id,
    start_time,
    end_time,
    title,
    sub_title,
    description,
    category,
    episode_title,
    episode_num,
    season_num,
    is_new,
    is_movie
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, channel_id, start_time, end_time, title, sub_title, description, category, episode_title, episode_num, season_num, is_new, is_movie, created_at
`

type CreateProgramParams struct {
	ChannelID    int64          `json:"channel_id"`
	StartTime    time.Time      `json:"start_time"`
	EndTime      time.Time      `json:"end_time"`
	Title        string         `json:"title"`
	SubTitle     sql.NullString `json:"sub_title"`
	Description  sql.NullString `json:"description"`
	Category     sql.NullString `json:"category"`
	EpisodeTitle sql.NullString `json:"episode_title"`
	EpisodeNum   sql.NullInt64  `json:"episode_num"`
	SeasonNum    sql.NullInt64  `json:"season_num"`
	IsNew        sql.NullInt64  `json:"is_new"`
	IsMovie      sql.NullInt64  `json:"is_movie"`
}

func (q *Queries) CreateProgram(ctx context.Context, arg CreateProgramParams) (LiveEpgProgram, error) {
	row := q.db.QueryRowContext(ctx, createProgram,
		arg.ChannelID,
		arg.StartTime,
		arg.EndTime,
		arg.Title,
		arg.SubTitle,
		arg.Description,
		arg.Category,
		arg.EpisodeTitle,
		arg.EpisodeNum,
		arg.SeasonNum,
		arg.IsNew,
		arg.IsMovie,
	)
	var i LiveEpgProgram
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.StartTime,
		&i.EndTime,
		&i.Title,
		&i.SubTitle,
		&i.Description,
		&i.Category,
		&i.EpisodeTitle,
		&i.EpisodeNum,
		&i.SeasonNum,
		&i.IsNew,
		&i.IsMovie,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldPrograms = `-- name: DeleteOldPrograms :exec
DELETE FROM live_epg_programs
WHERE end_time < $1
`

func (q *Queries) DeleteOldPrograms(ctx context.Context, endTime time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteOldPrograms, endTime)
	return err
}

const deleteProgramsByChannel = `-- name: DeleteProgramsByChannel :exec
DELETE FROM live_epg_programs
WHERE channel_id = $1
`

func (q *Queries) DeleteProgramsByChannel(ctx context.Context, channelID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProgramsByChannel, channelID)
	return err
}

const deleteProgramsByLibrary = `-- name: DeleteProgramsByLibrary :exec
DELETE FROM live_epg_programs
WHERE channel_id IN (SELECT id FROM live_channels WHERE library_id = $1)
`

func (q *Queries) DeleteProgramsByLibrary(ctx context.Context, libraryID int64) error {
	_, err := q.db.ExecContext(ctx, deleteProgramsByLibrary, libraryID)
	return err
}

const getCurrentProgram = `-- name: GetCurrentProgram :one
SELECT id, channel_id, start_time, end_time, title, sub_title, description, category, episode_title, episode_num, season_num, is_new, is_movie, created_at FROM live_epg_programs
WHERE channel_id = $1
  AND start_time <= $2
  AND end_time > $3
LIMIT 1
`

type GetCurrentProgramParams struct {
	ChannelID int64     `json:"channel_id"`
	StartTime time.Time `json:"start_time"`
	EndTime   time.Time `json:"end_time"`
}

func (q *Queries) GetCurrentProgram(ctx context.Context, arg GetCurrentProgramParams) (LiveEpgProgram, error) {
	row := q.db.QueryRowContext(ctx, getCurrentProgram, arg.ChannelID, arg.StartTime, arg.EndTime)
	var i LiveEpgProgram
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.StartTime,
		&i.EndTime,
		&i.Title,
		&i.SubTitle,
		&i.Description,
		&i.Category,
		&i.EpisodeTitle,
		&i.EpisodeNum,
		&i.SeasonNum,
		&i.IsNew,
		&i.IsMovie,
		&i.CreatedAt,
	)
	return i, err
}

const getProgram = `-- name: GetProgram :one
SELECT id, channel_id, start_time, end_time, title, sub_title, description, category, episode_title, episode_num, season_num, is_new, is_movie, created_at FROM live_epg_programs
WHERE id = $1
`

func (q *Queries) GetProgram(ctx context.Context, id int64) (LiveEpgProgram, error) {
	row := q.db.QueryRowContext(ctx, getProgram, id)
	var i LiveEpgProgram
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.StartTime,
		&i.EndTime,
		&i.Title,
		&i.SubTitle,
		&i.Description,
		&i.Category,
		&i.EpisodeTitle,
		&i.EpisodeNum,
		&i.SeasonNum,
		&i.IsNew,
		&i.IsMovie,
		&i.CreatedAt,
	)
	return i, err
}

const listProgramsByChannel = `-- name: ListProgramsByChannel :many
SELECT id, channel_id, start_time, end_time, title, sub_title, description, category, episode_title, episode_num, season_num, is_new, is_movie, created_at FROM live_epg_programs
WHERE channel_id = $1
  AND end_time > $2
  AND start_time < $3
ORDER BY start_time ASC
`

type ListProgramsByChannelParams struct {
	ChannelID int64     `json:"channel_id"`
	EndTime   time.Time `json:"end_time"`
	StartTime time.Time `json:"start_time"`
}

func (q *Queries) ListProgramsByChannel(ctx context.Context, arg ListProgramsByChannelParams) ([]LiveEpgProgram, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsByChannel, arg.ChannelID, arg.EndTime, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LiveEpgProgram{}
	for rows.Next() {
		var i LiveEpgProgram
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.StartTime,
			&i.EndTime,
			&i.Title,
			&i.SubTitle,
			&i.Description,
			&i.Category,
			&i.EpisodeTitle,
			&i.EpisodeNum,
			&i.SeasonNum,
			&i.IsNew,
			&i.IsMovie,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProgramsByLibrary = `-- name: ListProgramsByLibrary :many
SELECT p.id, p.channel_id, p.start_time, p.end_time, p.title, p.sub_title, p.description, p.category, p.episode_title, p.episode_num, p.season_num, p.is_new, p.is_movie, p.created_at FROM live_epg_programs p
JOIN live_channels c ON p.channel_id = c.id
WHERE c.library_id = $1
  AND p.end_time > $2
  AND p.start_time < $3
ORDER BY c.channel_number ASC, p.start_time ASC
`

type ListProgramsByLibraryParams struct {
	LibraryID int64     `json:"library_id"`
	EndTime   time.Time `json:"end_time"`
	StartTime time.Time `json:"start_time"`
}

func (q *Queries) ListProgramsByLibrary(ctx context.Context, arg ListProgramsByLibraryParams) ([]LiveEpgProgram, error) {
	rows, err := q.db.QueryContext(ctx, listProgramsByLibrary, arg.LibraryID, arg.EndTime, arg.StartTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LiveEpgProgram{}
	for rows.Next() {
		var i LiveEpgProgram
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.StartTime,
			&i.EndTime,
			&i.Title,
			&i.SubTitle,
			&i.Description,
			&i.Category,
			&i.EpisodeTitle,
			&i.EpisodeNum,
			&i.SeasonNum,
			&i.IsNew,
			&i.IsMovie,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
