/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as WebosRouteImport } from './routes/webos'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutLibrariesRouteImport } from './routes/_layout/libraries'
import { Route as WebosIndexRouteImport } from './routes/webos/index'
import { Route as LayoutLivetvIndexRouteImport } from './routes/_layout/livetv.index'
import { Route as LayoutLivetvEventRouteImport } from './routes/_layout/livetv.event'
import { Route as LayoutLivetvMappingsRouteImport } from './routes/_layout/livetv.mappings'
import { Route as LayoutLivetvPlayRouteImport } from './routes/_layout/livetv.play'
import { Route as LayoutMoviesIndexRouteImport } from './routes/_layout/movies.index'
import { Route as LayoutMoviesIdRouteImport } from './routes/_layout/movies.$id'
import { Route as LayoutMusicIndexRouteImport } from './routes/_layout/music.index'
import { Route as LayoutSettingsAccountRouteImport } from './routes/_layout/settings.account'
import { Route as LayoutSettingsDisplayRouteImport } from './routes/_layout/settings.display'
import { Route as LayoutSettingsEnrichmentQueueRouteImport } from './routes/_layout/settings.enrichment-queue'
import { Route as LayoutSettingsNitpickyRouteImport } from './routes/_layout/settings.nitpicky'
import { Route as LayoutSettingsPluginsRouteImport } from './routes/_layout/settings.plugins'
import { Route as LayoutSettingsPreferencesRouteImport } from './routes/_layout/settings.preferences'
import { Route as LayoutSettingsSchedulerRouteImport } from './routes/_layout/settings.scheduler'
import { Route as LayoutSettingsSystemRouteImport } from './routes/_layout/settings.system'
import { Route as LayoutSettingsUsersRouteImport } from './routes/_layout/settings.users'
import { Route as LayoutTvIndexRouteImport } from './routes/_layout/tv.index'
import { Route as WebosLivetvIndexRouteImport } from './routes/webos/livetv.index'
import { Route as WebosLivetvPlayRouteImport } from './routes/webos/livetv.play'
import { Route as WebosMoviesIndexRouteImport } from './routes/webos/movies.index'
import { Route as WebosMoviesIdRouteImport } from './routes/webos/movies.$id'
import { Route as WebosTvIndexRouteImport } from './routes/webos/tv.index'
import { Route as LayoutMusicAlbumsAlbumIdRouteImport } from './routes/_layout/music.albums.$albumId'
import { Route as LayoutMusicArtistsArtistIdRouteImport } from './routes/_layout/music.artists.$artistId'
import { Route as LayoutTvShowIdIndexRouteImport } from './routes/_layout/tv.$showId.index'
import { Route as WebosTvShowIdIndexRouteImport } from './routes/webos/tv.$showId.index'
import { Route as LayoutTvShowIdSeasonSeasonNumberRouteImport } from './routes/_layout/tv.$showId.season.$seasonNumber'
import { Route as WebosTvShowIdSeasonSeasonNumberRouteImport } from './routes/webos/tv.$showId.season.$seasonNumber'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const WebosRoute = WebosRouteImport.update({
  id: '/webos',
  path: '/webos',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLibrariesRoute = LayoutLibrariesRouteImport.update({
  id: '/libraries',
  path: '/libraries',
  getParentRoute: () => LayoutRoute,
} as any)
const WebosIndexRoute = WebosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WebosRoute,
} as any)
const LayoutLivetvIndexRoute = LayoutLivetvIndexRouteImport.update({
  id: '/livetv/',
  path: '/livetv/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLivetvEventRoute = LayoutLivetvEventRouteImport.update({
  id: '/livetv/event',
  path: '/livetv/event',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLivetvMappingsRoute = LayoutLivetvMappingsRouteImport.update({
  id: '/livetv/mappings',
  path: '/livetv/mappings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLivetvPlayRoute = LayoutLivetvPlayRouteImport.update({
  id: '/livetv/play',
  path: '/livetv/play',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMoviesIndexRoute = LayoutMoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMoviesIdRoute = LayoutMoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMusicIndexRoute = LayoutMusicIndexRouteImport.update({
  id: '/music/',
  path: '/music/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsAccountRoute = LayoutSettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsDisplayRoute = LayoutSettingsDisplayRouteImport.update({
  id: '/settings/display',
  path: '/settings/display',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsEnrichmentQueueRoute =
  LayoutSettingsEnrichmentQueueRouteImport.update({
    id: '/settings/enrichment-queue',
    path: '/settings/enrichment-queue',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSettingsNitpickyRoute = LayoutSettingsNitpickyRouteImport.update({
  id: '/settings/nitpicky',
  path: '/settings/nitpicky',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsPluginsRoute = LayoutSettingsPluginsRouteImport.update({
  id: '/settings/plugins',
  path: '/settings/plugins',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsPreferencesRoute =
  LayoutSettingsPreferencesRouteImport.update({
    id: '/settings/preferences',
    path: '/settings/preferences',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutSettingsSchedulerRoute = LayoutSettingsSchedulerRouteImport.update({
  id: '/settings/scheduler',
  path: '/settings/scheduler',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsSystemRoute = LayoutSettingsSystemRouteImport.update({
  id: '/settings/system',
  path: '/settings/system',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsUsersRoute = LayoutSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTvIndexRoute = LayoutTvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => LayoutRoute,
} as any)
const WebosLivetvIndexRoute = WebosLivetvIndexRouteImport.update({
  id: '/livetv/',
  path: '/livetv/',
  getParentRoute: () => WebosRoute,
} as any)
const WebosLivetvPlayRoute = WebosLivetvPlayRouteImport.update({
  id: '/livetv/play',
  path: '/livetv/play',
  getParentRoute: () => WebosRoute,
} as any)
const WebosMoviesIndexRoute = WebosMoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => WebosRoute,
} as any)
const WebosMoviesIdRoute = WebosMoviesIdRouteImport.update({
  id: '/movies/$id',
  path: '/movies/$id',
  getParentRoute: () => WebosRoute,
} as any)
const WebosTvIndexRoute = WebosTvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => WebosRoute,
} as any)
const LayoutMusicAlbumsAlbumIdRoute =
  LayoutMusicAlbumsAlbumIdRouteImport.update({
    id: '/music/albums/$albumId',
    path: '/music/albums/$albumId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutMusicArtistsArtistIdRoute =
  LayoutMusicArtistsArtistIdRouteImport.update({
    id: '/music/artists/$artistId',
    path: '/music/artists/$artistId',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutTvShowIdIndexRoute = LayoutTvShowIdIndexRouteImport.update({
  id: '/tv/$showId/',
  path: '/tv/$showId/',
  getParentRoute: () => LayoutRoute,
} as any)
const WebosTvShowIdIndexRoute = WebosTvShowIdIndexRouteImport.update({
  id: '/tv/$showId/',
  path: '/tv/$showId/',
  getParentRoute: () => WebosRoute,
} as any)
const LayoutTvShowIdSeasonSeasonNumberRoute =
  LayoutTvShowIdSeasonSeasonNumberRouteImport.update({
    id: '/tv/$showId/season/$seasonNumber',
    path: '/tv/$showId/season/$seasonNumber',
    getParentRoute: () => LayoutRoute,
  } as any)
const WebosTvShowIdSeasonSeasonNumberRoute =
  WebosTvShowIdSeasonSeasonNumberRouteImport.update({
    id: '/tv/$showId/season/$seasonNumber',
    path: '/tv/$showId/season/$seasonNumber',
    getParentRoute: () => WebosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/webos': typeof WebosRouteWithChildren
  '/libraries': typeof LayoutLibrariesRoute
  '/webos/': typeof WebosIndexRoute
  '/livetv/event': typeof LayoutLivetvEventRoute
  '/livetv/mappings': typeof LayoutLivetvMappingsRoute
  '/livetv/play': typeof LayoutLivetvPlayRoute
  '/movies/$id': typeof LayoutMoviesIdRoute
  '/settings/account': typeof LayoutSettingsAccountRoute
  '/settings/display': typeof LayoutSettingsDisplayRoute
  '/settings/enrichment-queue': typeof LayoutSettingsEnrichmentQueueRoute
  '/settings/nitpicky': typeof LayoutSettingsNitpickyRoute
  '/settings/plugins': typeof LayoutSettingsPluginsRoute
  '/settings/preferences': typeof LayoutSettingsPreferencesRoute
  '/settings/scheduler': typeof LayoutSettingsSchedulerRoute
  '/settings/system': typeof LayoutSettingsSystemRoute
  '/settings/users': typeof LayoutSettingsUsersRoute
  '/webos/livetv/play': typeof WebosLivetvPlayRoute
  '/webos/movies/$id': typeof WebosMoviesIdRoute
  '/livetv/': typeof LayoutLivetvIndexRoute
  '/movies/': typeof LayoutMoviesIndexRoute
  '/music/': typeof LayoutMusicIndexRoute
  '/tv/': typeof LayoutTvIndexRoute
  '/webos/livetv/': typeof WebosLivetvIndexRoute
  '/webos/movies/': typeof WebosMoviesIndexRoute
  '/webos/tv/': typeof WebosTvIndexRoute
  '/music/albums/$albumId': typeof LayoutMusicAlbumsAlbumIdRoute
  '/music/artists/$artistId': typeof LayoutMusicArtistsArtistIdRoute
  '/tv/$showId/': typeof LayoutTvShowIdIndexRoute
  '/webos/tv/$showId/': typeof WebosTvShowIdIndexRoute
  '/tv/$showId/season/$seasonNumber': typeof LayoutTvShowIdSeasonSeasonNumberRoute
  '/webos/tv/$showId/season/$seasonNumber': typeof WebosTvShowIdSeasonSeasonNumberRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/libraries': typeof LayoutLibrariesRoute
  '/': typeof LayoutIndexRoute
  '/webos': typeof WebosIndexRoute
  '/livetv/event': typeof LayoutLivetvEventRoute
  '/livetv/mappings': typeof LayoutLivetvMappingsRoute
  '/livetv/play': typeof LayoutLivetvPlayRoute
  '/movies/$id': typeof LayoutMoviesIdRoute
  '/settings/account': typeof LayoutSettingsAccountRoute
  '/settings/display': typeof LayoutSettingsDisplayRoute
  '/settings/enrichment-queue': typeof LayoutSettingsEnrichmentQueueRoute
  '/settings/nitpicky': typeof LayoutSettingsNitpickyRoute
  '/settings/plugins': typeof LayoutSettingsPluginsRoute
  '/settings/preferences': typeof LayoutSettingsPreferencesRoute
  '/settings/scheduler': typeof LayoutSettingsSchedulerRoute
  '/settings/system': typeof LayoutSettingsSystemRoute
  '/settings/users': typeof LayoutSettingsUsersRoute
  '/webos/livetv/play': typeof WebosLivetvPlayRoute
  '/webos/movies/$id': typeof WebosMoviesIdRoute
  '/livetv': typeof LayoutLivetvIndexRoute
  '/movies': typeof LayoutMoviesIndexRoute
  '/music': typeof LayoutMusicIndexRoute
  '/tv': typeof LayoutTvIndexRoute
  '/webos/livetv': typeof WebosLivetvIndexRoute
  '/webos/movies': typeof WebosMoviesIndexRoute
  '/webos/tv': typeof WebosTvIndexRoute
  '/music/albums/$albumId': typeof LayoutMusicAlbumsAlbumIdRoute
  '/music/artists/$artistId': typeof LayoutMusicArtistsArtistIdRoute
  '/tv/$showId': typeof LayoutTvShowIdIndexRoute
  '/webos/tv/$showId': typeof WebosTvShowIdIndexRoute
  '/tv/$showId/season/$seasonNumber': typeof LayoutTvShowIdSeasonSeasonNumberRoute
  '/webos/tv/$showId/season/$seasonNumber': typeof WebosTvShowIdSeasonSeasonNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/webos': typeof WebosRouteWithChildren
  '/_layout/libraries': typeof LayoutLibrariesRoute
  '/_layout/': typeof LayoutIndexRoute
  '/webos/': typeof WebosIndexRoute
  '/_layout/livetv/event': typeof LayoutLivetvEventRoute
  '/_layout/livetv/mappings': typeof LayoutLivetvMappingsRoute
  '/_layout/livetv/play': typeof LayoutLivetvPlayRoute
  '/_layout/movies/$id': typeof LayoutMoviesIdRoute
  '/_layout/settings/account': typeof LayoutSettingsAccountRoute
  '/_layout/settings/display': typeof LayoutSettingsDisplayRoute
  '/_layout/settings/enrichment-queue': typeof LayoutSettingsEnrichmentQueueRoute
  '/_layout/settings/nitpicky': typeof LayoutSettingsNitpickyRoute
  '/_layout/settings/plugins': typeof LayoutSettingsPluginsRoute
  '/_layout/settings/preferences': typeof LayoutSettingsPreferencesRoute
  '/_layout/settings/scheduler': typeof LayoutSettingsSchedulerRoute
  '/_layout/settings/system': typeof LayoutSettingsSystemRoute
  '/_layout/settings/users': typeof LayoutSettingsUsersRoute
  '/webos/livetv/play': typeof WebosLivetvPlayRoute
  '/webos/movies/$id': typeof WebosMoviesIdRoute
  '/_layout/livetv/': typeof LayoutLivetvIndexRoute
  '/_layout/movies/': typeof LayoutMoviesIndexRoute
  '/_layout/music/': typeof LayoutMusicIndexRoute
  '/_layout/tv/': typeof LayoutTvIndexRoute
  '/webos/livetv/': typeof WebosLivetvIndexRoute
  '/webos/movies/': typeof WebosMoviesIndexRoute
  '/webos/tv/': typeof WebosTvIndexRoute
  '/_layout/music/albums/$albumId': typeof LayoutMusicAlbumsAlbumIdRoute
  '/_layout/music/artists/$artistId': typeof LayoutMusicArtistsArtistIdRoute
  '/_layout/tv/$showId/': typeof LayoutTvShowIdIndexRoute
  '/webos/tv/$showId/': typeof WebosTvShowIdIndexRoute
  '/_layout/tv/$showId/season/$seasonNumber': typeof LayoutTvShowIdSeasonSeasonNumberRoute
  '/webos/tv/$showId/season/$seasonNumber': typeof WebosTvShowIdSeasonSeasonNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/webos'
    | '/libraries'
    | '/webos/'
    | '/livetv/event'
    | '/livetv/mappings'
    | '/livetv/play'
    | '/movies/$id'
    | '/settings/account'
    | '/settings/display'
    | '/settings/enrichment-queue'
    | '/settings/nitpicky'
    | '/settings/plugins'
    | '/settings/preferences'
    | '/settings/scheduler'
    | '/settings/system'
    | '/settings/users'
    | '/webos/livetv/play'
    | '/webos/movies/$id'
    | '/livetv/'
    | '/movies/'
    | '/music/'
    | '/tv/'
    | '/webos/livetv/'
    | '/webos/movies/'
    | '/webos/tv/'
    | '/music/albums/$albumId'
    | '/music/artists/$artistId'
    | '/tv/$showId/'
    | '/webos/tv/$showId/'
    | '/tv/$showId/season/$seasonNumber'
    | '/webos/tv/$showId/season/$seasonNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/libraries'
    | '/'
    | '/webos'
    | '/livetv/event'
    | '/livetv/mappings'
    | '/livetv/play'
    | '/movies/$id'
    | '/settings/account'
    | '/settings/display'
    | '/settings/enrichment-queue'
    | '/settings/nitpicky'
    | '/settings/plugins'
    | '/settings/preferences'
    | '/settings/scheduler'
    | '/settings/system'
    | '/settings/users'
    | '/webos/livetv/play'
    | '/webos/movies/$id'
    | '/livetv'
    | '/movies'
    | '/music'
    | '/tv'
    | '/webos/livetv'
    | '/webos/movies'
    | '/webos/tv'
    | '/music/albums/$albumId'
    | '/music/artists/$artistId'
    | '/tv/$showId'
    | '/webos/tv/$showId'
    | '/tv/$showId/season/$seasonNumber'
    | '/webos/tv/$showId/season/$seasonNumber'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/setup'
    | '/webos'
    | '/_layout/libraries'
    | '/_layout/'
    | '/webos/'
    | '/_layout/livetv/event'
    | '/_layout/livetv/mappings'
    | '/_layout/livetv/play'
    | '/_layout/movies/$id'
    | '/_layout/settings/account'
    | '/_layout/settings/display'
    | '/_layout/settings/enrichment-queue'
    | '/_layout/settings/nitpicky'
    | '/_layout/settings/plugins'
    | '/_layout/settings/preferences'
    | '/_layout/settings/scheduler'
    | '/_layout/settings/system'
    | '/_layout/settings/users'
    | '/webos/livetv/play'
    | '/webos/movies/$id'
    | '/_layout/livetv/'
    | '/_layout/movies/'
    | '/_layout/music/'
    | '/_layout/tv/'
    | '/webos/livetv/'
    | '/webos/movies/'
    | '/webos/tv/'
    | '/_layout/music/albums/$albumId'
    | '/_layout/music/artists/$artistId'
    | '/_layout/tv/$showId/'
    | '/webos/tv/$showId/'
    | '/_layout/tv/$showId/season/$seasonNumber'
    | '/webos/tv/$showId/season/$seasonNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  WebosRoute: typeof WebosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webos': {
      id: '/webos'
      path: '/webos'
      fullPath: '/webos'
      preLoaderRoute: typeof WebosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/libraries': {
      id: '/_layout/libraries'
      path: '/libraries'
      fullPath: '/libraries'
      preLoaderRoute: typeof LayoutLibrariesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/webos/': {
      id: '/webos/'
      path: '/'
      fullPath: '/webos/'
      preLoaderRoute: typeof WebosIndexRouteImport
      parentRoute: typeof WebosRoute
    }
    '/_layout/livetv/': {
      id: '/_layout/livetv/'
      path: '/livetv'
      fullPath: '/livetv/'
      preLoaderRoute: typeof LayoutLivetvIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/livetv/event': {
      id: '/_layout/livetv/event'
      path: '/livetv/event'
      fullPath: '/livetv/event'
      preLoaderRoute: typeof LayoutLivetvEventRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/livetv/mappings': {
      id: '/_layout/livetv/mappings'
      path: '/livetv/mappings'
      fullPath: '/livetv/mappings'
      preLoaderRoute: typeof LayoutLivetvMappingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/livetv/play': {
      id: '/_layout/livetv/play'
      path: '/livetv/play'
      fullPath: '/livetv/play'
      preLoaderRoute: typeof LayoutLivetvPlayRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/movies/': {
      id: '/_layout/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof LayoutMoviesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/movies/$id': {
      id: '/_layout/movies/$id'
      path: '/movies/$id'
      fullPath: '/movies/$id'
      preLoaderRoute: typeof LayoutMoviesIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/music/': {
      id: '/_layout/music/'
      path: '/music'
      fullPath: '/music/'
      preLoaderRoute: typeof LayoutMusicIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/account': {
      id: '/_layout/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof LayoutSettingsAccountRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/display': {
      id: '/_layout/settings/display'
      path: '/settings/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof LayoutSettingsDisplayRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/enrichment-queue': {
      id: '/_layout/settings/enrichment-queue'
      path: '/settings/enrichment-queue'
      fullPath: '/settings/enrichment-queue'
      preLoaderRoute: typeof LayoutSettingsEnrichmentQueueRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/nitpicky': {
      id: '/_layout/settings/nitpicky'
      path: '/settings/nitpicky'
      fullPath: '/settings/nitpicky'
      preLoaderRoute: typeof LayoutSettingsNitpickyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/plugins': {
      id: '/_layout/settings/plugins'
      path: '/settings/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof LayoutSettingsPluginsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/preferences': {
      id: '/_layout/settings/preferences'
      path: '/settings/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof LayoutSettingsPreferencesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/scheduler': {
      id: '/_layout/settings/scheduler'
      path: '/settings/scheduler'
      fullPath: '/settings/scheduler'
      preLoaderRoute: typeof LayoutSettingsSchedulerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/system': {
      id: '/_layout/settings/system'
      path: '/settings/system'
      fullPath: '/settings/system'
      preLoaderRoute: typeof LayoutSettingsSystemRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/users': {
      id: '/_layout/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof LayoutSettingsUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tv/': {
      id: '/_layout/tv/'
      path: '/tv'
      fullPath: '/tv/'
      preLoaderRoute: typeof LayoutTvIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/webos/livetv/': {
      id: '/webos/livetv/'
      path: '/livetv'
      fullPath: '/webos/livetv/'
      preLoaderRoute: typeof WebosLivetvIndexRouteImport
      parentRoute: typeof WebosRoute
    }
    '/webos/livetv/play': {
      id: '/webos/livetv/play'
      path: '/livetv/play'
      fullPath: '/webos/livetv/play'
      preLoaderRoute: typeof WebosLivetvPlayRouteImport
      parentRoute: typeof WebosRoute
    }
    '/webos/movies/': {
      id: '/webos/movies/'
      path: '/movies'
      fullPath: '/webos/movies/'
      preLoaderRoute: typeof WebosMoviesIndexRouteImport
      parentRoute: typeof WebosRoute
    }
    '/webos/movies/$id': {
      id: '/webos/movies/$id'
      path: '/movies/$id'
      fullPath: '/webos/movies/$id'
      preLoaderRoute: typeof WebosMoviesIdRouteImport
      parentRoute: typeof WebosRoute
    }
    '/webos/tv/': {
      id: '/webos/tv/'
      path: '/tv'
      fullPath: '/webos/tv/'
      preLoaderRoute: typeof WebosTvIndexRouteImport
      parentRoute: typeof WebosRoute
    }
    '/_layout/music/albums/$albumId': {
      id: '/_layout/music/albums/$albumId'
      path: '/music/albums/$albumId'
      fullPath: '/music/albums/$albumId'
      preLoaderRoute: typeof LayoutMusicAlbumsAlbumIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/music/artists/$artistId': {
      id: '/_layout/music/artists/$artistId'
      path: '/music/artists/$artistId'
      fullPath: '/music/artists/$artistId'
      preLoaderRoute: typeof LayoutMusicArtistsArtistIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/tv/$showId/': {
      id: '/_layout/tv/$showId/'
      path: '/tv/$showId'
      fullPath: '/tv/$showId/'
      preLoaderRoute: typeof LayoutTvShowIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/webos/tv/$showId/': {
      id: '/webos/tv/$showId/'
      path: '/tv/$showId'
      fullPath: '/webos/tv/$showId/'
      preLoaderRoute: typeof WebosTvShowIdIndexRouteImport
      parentRoute: typeof WebosRoute
    }
    '/_layout/tv/$showId/season/$seasonNumber': {
      id: '/_layout/tv/$showId/season/$seasonNumber'
      path: '/tv/$showId/season/$seasonNumber'
      fullPath: '/tv/$showId/season/$seasonNumber'
      preLoaderRoute: typeof LayoutTvShowIdSeasonSeasonNumberRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/webos/tv/$showId/season/$seasonNumber': {
      id: '/webos/tv/$showId/season/$seasonNumber'
      path: '/tv/$showId/season/$seasonNumber'
      fullPath: '/webos/tv/$showId/season/$seasonNumber'
      preLoaderRoute: typeof WebosTvShowIdSeasonSeasonNumberRouteImport
      parentRoute: typeof WebosRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutLibrariesRoute: typeof LayoutLibrariesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutLivetvEventRoute: typeof LayoutLivetvEventRoute
  LayoutLivetvMappingsRoute: typeof LayoutLivetvMappingsRoute
  LayoutLivetvPlayRoute: typeof LayoutLivetvPlayRoute
  LayoutMoviesIdRoute: typeof LayoutMoviesIdRoute
  LayoutSettingsAccountRoute: typeof LayoutSettingsAccountRoute
  LayoutSettingsDisplayRoute: typeof LayoutSettingsDisplayRoute
  LayoutSettingsEnrichmentQueueRoute: typeof LayoutSettingsEnrichmentQueueRoute
  LayoutSettingsNitpickyRoute: typeof LayoutSettingsNitpickyRoute
  LayoutSettingsPluginsRoute: typeof LayoutSettingsPluginsRoute
  LayoutSettingsPreferencesRoute: typeof LayoutSettingsPreferencesRoute
  LayoutSettingsSchedulerRoute: typeof LayoutSettingsSchedulerRoute
  LayoutSettingsSystemRoute: typeof LayoutSettingsSystemRoute
  LayoutSettingsUsersRoute: typeof LayoutSettingsUsersRoute
  LayoutLivetvIndexRoute: typeof LayoutLivetvIndexRoute
  LayoutMoviesIndexRoute: typeof LayoutMoviesIndexRoute
  LayoutMusicIndexRoute: typeof LayoutMusicIndexRoute
  LayoutTvIndexRoute: typeof LayoutTvIndexRoute
  LayoutMusicAlbumsAlbumIdRoute: typeof LayoutMusicAlbumsAlbumIdRoute
  LayoutMusicArtistsArtistIdRoute: typeof LayoutMusicArtistsArtistIdRoute
  LayoutTvShowIdIndexRoute: typeof LayoutTvShowIdIndexRoute
  LayoutTvShowIdSeasonSeasonNumberRoute: typeof LayoutTvShowIdSeasonSeasonNumberRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutLibrariesRoute: LayoutLibrariesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutLivetvEventRoute: LayoutLivetvEventRoute,
  LayoutLivetvMappingsRoute: LayoutLivetvMappingsRoute,
  LayoutLivetvPlayRoute: LayoutLivetvPlayRoute,
  LayoutMoviesIdRoute: LayoutMoviesIdRoute,
  LayoutSettingsAccountRoute: LayoutSettingsAccountRoute,
  LayoutSettingsDisplayRoute: LayoutSettingsDisplayRoute,
  LayoutSettingsEnrichmentQueueRoute: LayoutSettingsEnrichmentQueueRoute,
  LayoutSettingsNitpickyRoute: LayoutSettingsNitpickyRoute,
  LayoutSettingsPluginsRoute: LayoutSettingsPluginsRoute,
  LayoutSettingsPreferencesRoute: LayoutSettingsPreferencesRoute,
  LayoutSettingsSchedulerRoute: LayoutSettingsSchedulerRoute,
  LayoutSettingsSystemRoute: LayoutSettingsSystemRoute,
  LayoutSettingsUsersRoute: LayoutSettingsUsersRoute,
  LayoutLivetvIndexRoute: LayoutLivetvIndexRoute,
  LayoutMoviesIndexRoute: LayoutMoviesIndexRoute,
  LayoutMusicIndexRoute: LayoutMusicIndexRoute,
  LayoutTvIndexRoute: LayoutTvIndexRoute,
  LayoutMusicAlbumsAlbumIdRoute: LayoutMusicAlbumsAlbumIdRoute,
  LayoutMusicArtistsArtistIdRoute: LayoutMusicArtistsArtistIdRoute,
  LayoutTvShowIdIndexRoute: LayoutTvShowIdIndexRoute,
  LayoutTvShowIdSeasonSeasonNumberRoute: LayoutTvShowIdSeasonSeasonNumberRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface WebosRouteChildren {
  WebosIndexRoute: typeof WebosIndexRoute
  WebosLivetvPlayRoute: typeof WebosLivetvPlayRoute
  WebosMoviesIdRoute: typeof WebosMoviesIdRoute
  WebosLivetvIndexRoute: typeof WebosLivetvIndexRoute
  WebosMoviesIndexRoute: typeof WebosMoviesIndexRoute
  WebosTvIndexRoute: typeof WebosTvIndexRoute
  WebosTvShowIdIndexRoute: typeof WebosTvShowIdIndexRoute
  WebosTvShowIdSeasonSeasonNumberRoute: typeof WebosTvShowIdSeasonSeasonNumberRoute
}

const WebosRouteChildren: WebosRouteChildren = {
  WebosIndexRoute: WebosIndexRoute,
  WebosLivetvPlayRoute: WebosLivetvPlayRoute,
  WebosMoviesIdRoute: WebosMoviesIdRoute,
  WebosLivetvIndexRoute: WebosLivetvIndexRoute,
  WebosMoviesIndexRoute: WebosMoviesIndexRoute,
  WebosTvIndexRoute: WebosTvIndexRoute,
  WebosTvShowIdIndexRoute: WebosTvShowIdIndexRoute,
  WebosTvShowIdSeasonSeasonNumberRoute: WebosTvShowIdSeasonSeasonNumberRoute,
}

const WebosRouteWithChildren = WebosRoute._addFileChildren(WebosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  WebosRoute: WebosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
